class SiteStats
  include JSON::Serializable

  alias Langname = String

  @@lang_aliases = {
    "agda"         => "Agda",
    "awk"          => "AWK",
    "bash"         => "Bash",
    "bf"           => "BF",
    "brainfuck"    => "BF",
    "c"            => "C",
    "c++"          => "C++",
    "cpp"          => "C++",
    "csharp"       => "C#",
    "c#"           => "C#",
    "clojure"      => "Clojure",
    "cobol"        => "COBOL",
    "coffeescript" => "CoffeeScript",
    "commonlisp"   => "Lisp",
    "coq"          => "Coq",
    "crystal"      => "Crystal",
    "d"            => "D",
    "dart"         => "Dart",
    "elixir"       => "Elixir",
    "erlang"       => "Erlang",
    "elm"          => "Elm",
    "factor"       => "Factor",
    "fish"         => "><>",
    "forth"        => "Forth",
    "fortran"      => "Fortran",
    "fsharp"       => "F#",
    "f#"           => "F#",
    "golang"       => "Go",
    "go"           => "Go",
    "groovy"       => "Groovy",
    "haskell"      => "Haskell",
    "haxe"         => "Haxe",
    "hexagony"     => "Hexagony",
    "idris"        => "Idris",
    "j"            => "J",
    "julia"        => "Julia",
    "janet"        => "Janet",
    "java"         => "Java",
    "javascript"   => "JS",
    "js"           => "JS",
    "k"            => "K",
    "kotlin"       => "Kotlin",
    "lisp"         => "Lisp",
    "lua"          => "Lua",
    "mysql"        => "SQL",
    "nim"          => "Nim",
    "objectivec"   => "Obj-C",
    "objc"         => "Obj-C",
    "ocaml"        => "OCaml",
    "pascal"       => "Pascal",
    "perl"         => "Perl",
    "php"          => "PHP",
    "powershell"   => "PowerShell",
    "prolog"       => "Prolog",
    "purescript"   => "PureScript",
    "python"       => "Python",
    "python2"      => "Python",
    "python3"      => "Python",
    "r"            => "R",
    "racket"       => "Racket",
    "raku"         => "Raku",
    "reason"       => "Reason",
    "ruby"         => "Ruby",
    "rust"         => "Rust",
    "scala"        => "Scala",
    "scheme"       => "Scheme",
    "solidity"     => "Solidity",
    "sql"          => "SQL",
    "swift"        => "Swift",
    "tcl"          => "Tcl",
    "tex"          => "Tex",
    "typescript"   => "TS",
    "ts"           => "TS",
    "v"            => "V",
    "vb"           => "VB",
    "viml"         => "VimL",
    "wren"         => "Wren",
    "zig"          => "Zig",
  }

  def initialize(
    @username : String,
    @profile_url : String,
    @solved_by_language : Hash(Langname, Int32)
  )
    @solved_by_language = @solved_by_language.transform_keys do |lang|
      @@lang_aliases.fetch(lang.downcase.gsub(/[\s-]/, ""), lang)
    end
  end
end
